{"name": "Ошибка при получении заказа c несуществующим номером", "status": "passed", "steps": [{"name": "Создаём заказ", "status": "passed", "start": 1747825205447, "stop": 1747825205655}, {"name": "Получение заказа", "status": "passed", "start": 1747825205655, "stop": 1747825205848}], "start": 1747825205447, "stop": 1747825205848, "uuid": "c2ca7988-0087-40fb-8905-9dd1c70fc494", "historyId": "76b8c0e35c7b63a6b6342197c73d4827", "testCaseId": "76b8c0e35c7b63a6b6342197c73d4827", "fullName": "tests.test_receiving_order_by_track.TestReceivingOrderByTrack#test_error_receiving_order_non_existent_track", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_receiving_order_by_track"}, {"name": "subSuite", "value": "TestReceivingOrderByTrack"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "7628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_receiving_order_by_track"}]}