{"name": "Ошибка '404' при авторизации с несуществующем логином или паролем", "status": "passed", "steps": [{"name": "Создаём курьера", "status": "passed", "start": 1747765802399, "stop": 1747765802577}, {"name": "Авторизуемся курьером", "status": "passed", "start": 1747765802577, "stop": 1747765802773}], "start": 1747765802399, "stop": 1747765802775, "uuid": "a4150130-d5c1-477d-bf0f-aca622f4cb2a", "historyId": "fb3fafaee8ce840031e14754f5109840", "testCaseId": "fb3fafaee8ce840031e14754f5109840", "fullName": "tests.test_login_courier.TestLoginCourier#test_error_when_logging_in_with_an_incorrect_login_or_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "8692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}