{"name": "Ошибка '404' при отправки запроса с несуществующем id на удаление курьера", "status": "broken", "statusDetails": {"message": "KeyError: 'id'", "trace": "@pytest.fixture\n    def creating_courier_and_receiving_id():\n        body = DataForCreationCourier.CREATION_COURIER_BODY\n        CourierMethods.created_courier(body)\n        login = body[\"login\"]\n        password = body[\"password\"]\n>       courier_id = CourierMethods.receiving_id_courier(login, password).json()[\"id\"]\nE       KeyError: 'id'\n\nconftest.py:30: KeyError"}, "start": 1747763410886, "stop": 1747763410886, "uuid": "9bbe0a0b-bd73-49c1-8000-721f2daad8bc", "historyId": "86fed0cfe787b4d4fc9e7470d8378f86", "testCaseId": "86fed0cfe787b4d4fc9e7470d8378f86", "fullName": "tests.test_deleted_courier.TestDeletedCourier#test_error_request_without_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_deleted_courier"}, {"name": "subSuite", "value": "TestDeletedCourier"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "6036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_deleted_courier"}]}