{"name": "Ошибка при получении заказа c несуществующим номером", "status": "passed", "steps": [{"name": "Создаём заказ", "status": "passed", "start": 1747825013373, "stop": 1747825013515}, {"name": "Получение заказа", "status": "passed", "start": 1747825013515, "stop": 1747825013673}], "start": 1747825013373, "stop": 1747825013674, "uuid": "c1130681-51a2-4918-8d19-c2ca11bfb998", "historyId": "76b8c0e35c7b63a6b6342197c73d4827", "testCaseId": "76b8c0e35c7b63a6b6342197c73d4827", "fullName": "tests.test_receiving_order_by_track.TestReceivingOrderByTrack#test_error_receiving_order_non_existent_track", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_receiving_order_by_track"}, {"name": "subSuite", "value": "TestReceivingOrderByTrack"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "3424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_receiving_order_by_track"}]}