{"name": "Ошибка при получении заказа c несуществующим номером", "status": "passed", "steps": [{"name": "Создаём заказ", "status": "passed", "start": 1747763965541, "stop": 1747763965763}, {"name": "Получение заказа", "status": "passed", "start": 1747763965763, "stop": 1747763965925}], "start": 1747763965541, "stop": 1747763965926, "uuid": "d3f4dac4-8b32-4041-b841-750362f2c844", "historyId": "76b8c0e35c7b63a6b6342197c73d4827", "testCaseId": "76b8c0e35c7b63a6b6342197c73d4827", "fullName": "tests.test_receiving_order_by_track.TestReceivingOrderByTrack#test_error_receiving_order_non_existent_track", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_receiving_order_by_track"}, {"name": "subSuite", "value": "TestReceivingOrderByTrack"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "9628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_receiving_order_by_track"}]}