{"name": "Ошибка '404' при авторизации с несуществующем логином или паролем", "status": "passed", "steps": [{"name": "Создаём курьера", "status": "passed", "start": 1747825008118, "stop": 1747825008323}, {"name": "Авторизуемся курьером", "status": "passed", "start": 1747825008323, "stop": 1747825008496}], "start": 1747825008118, "stop": 1747825008497, "uuid": "cfd80309-53e5-49b3-8f42-91d397a9bd62", "historyId": "fb3fafaee8ce840031e14754f5109840", "testCaseId": "fb3fafaee8ce840031e14754f5109840", "fullName": "tests.test_login_courier.TestLoginCourier#test_error_when_logging_in_with_an_incorrect_login_or_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "3424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}