{"name": "Ошибка 404 при отправки запроса принятие заказа с невалидным id курьера", "status": "failed", "statusDetails": {"message": "AssertionError: assert {'code': 500,...onse [200]>\"'} == {'code': 404,...е существует'}\n  \n  Differing items:\n  {'code': 500} != {'code': 404}\n  {'message': 'invalid input syntax for type integer: \"<Response [200]>\"'} != {'message': 'Курьера с таким id не существует'}\n  Use -v to get more diff", "trace": "self = <tests.test_accept_the_order.TestAcceptTheOrder object at 0x000001E7285AF410>, creating_courier_and_creating_order = [524453, <Response [200]>]\n\n    @allure.title(\"Ошибка 404 при отправки запроса принятие заказа с невалидным id курьера\")\n    def test_error_accept_the_order_invalid_id_courier(self, creating_courier_and_creating_order):\n        with allure.step(\"Принятие заказа\"):\n            courier_id = 1\n            order_id = creating_courier_and_creating_order[1]\n            response = OrderMethods.accept_the_order(order_id, courier_id).json()\n>           assert response == {'code': 404, 'message': 'Курьера с таким id не существует'}\nE           assert {'code': 500,...onse [200]>\"'} == {'code': 404,...е существует'}\nE             \nE             Differing items:\nE             {'code': 500} != {'code': 404}\nE             {'message': 'invalid input syntax for type integer: \"<Response [200]>\"'} != {'message': 'Курьера с таким id не существует'}\nE             Use -v to get more diff\n\ntests\\test_accept_the_order.py:46: AssertionError"}, "steps": [{"name": "Принятие заказа", "status": "failed", "statusDetails": {"message": "AssertionError: assert {'code': 500,...onse [200]>\"'} == {'code': 404,...е существует'}\n  \n  Differing items:\n  {'code': 500} != {'code': 404}\n  {'message': 'invalid input syntax for type integer: \"<Response [200]>\"'} != {'message': 'Курьера с таким id не существует'}\n  Use -v to get more diff\n", "trace": "  File \"C:\\Users\\Serega\\Git project\\Sprint_7\\tests\\test_accept_the_order.py\", line 46, in test_error_accept_the_order_invalid_id_courier\n    assert response == {'code': 404, 'message': 'Курьера с таким id не существует'}\n"}, "start": 1747762665434, "stop": 1747762665604}], "start": 1747762665434, "stop": 1747762665606, "uuid": "0b4ba60d-f04a-4993-889a-ecb5119f01d6", "historyId": "91bdcecb318177ee160d45e11a7816a1", "testCaseId": "91bdcecb318177ee160d45e11a7816a1", "fullName": "tests.test_accept_the_order.TestAcceptTheOrder#test_error_accept_the_order_invalid_id_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_the_order"}, {"name": "subSuite", "value": "TestAcceptTheOrder"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "7720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_the_order"}]}