{"name": "Ошибка '404' при авторизации с несуществующем логином или паролем", "status": "passed", "steps": [{"name": "Создаём курьера", "status": "passed", "start": 1747825200058, "stop": 1747825200210}, {"name": "Авторизуемся курьером", "status": "passed", "start": 1747825200210, "stop": 1747825200397}], "start": 1747825200058, "stop": 1747825200398, "uuid": "b0e0e557-e61c-4973-a099-03b852dcd088", "historyId": "fb3fafaee8ce840031e14754f5109840", "testCaseId": "fb3fafaee8ce840031e14754f5109840", "fullName": "tests.test_login_courier.TestLoginCourier#test_error_when_logging_in_with_an_incorrect_login_or_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "7628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}