{"name": "Ошибка 404 при отправки запроса принятие заказа с невалидным id заказа", "status": "passed", "steps": [{"name": "Принятие заказа", "status": "passed", "start": 1747763954166, "stop": 1747763954380}], "start": 1747763954165, "stop": 1747763954380, "uuid": "432487ec-6569-4e4c-9ad7-5e45d5e3bf95", "historyId": "85164a658ac696fd8eefc5407e1a2a9a", "testCaseId": "85164a658ac696fd8eefc5407e1a2a9a", "fullName": "tests.test_accept_the_order.TestAcceptTheOrder#test_error_accept_the_order_invalid_id_order", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_the_order"}, {"name": "subSuite", "value": "TestAcceptTheOrder"}, {"name": "host", "value": "KOMPUTER"}, {"name": "thread", "value": "9628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_the_order"}]}